Added gpt-oss to sweep.

diff --git a/.github/workflows/gpu-sweep-test.yml b/.github/workflows/gpu-sweep-test.yml
--- a/.github/workflows/gpu-sweep-test.yml
+++ b/.github/workflows/gpu-sweep-test.yml
@@ -28,6 +28,8 @@ on:
           - 'kedarpotdar147/vllm:05'
           - 'rocm/vllm-dev:nightly_official_0729_rc1_20250718'
           - 'rocm/7.0-preview:rocm7.0_preview_ubuntu_22.04_vllm_0.9.1_mi35x_alpha'
+          - 'rocm/vllm-dev:open-mi300-08052025'
+          - 'rocm/vllm-dev:open-mi355-08052025'
           - 'nvcr.io#nvidia/tensorrt-llm/release:1.1.0rc2'
 
       image-dsr1:
@@ -162,6 +164,64 @@ jobs:
           echo "MODEL=deepseek-ai/DeepSeek-R1-0528" >> $GITHUB_ENV
 
       - name: Launch job script - DSR1
+        run: |
+          RUNNER_NAME=${{ runner.name }}
+          bash ./runners/launch_${RUNNER_NAME%%_*}*.sh ${{ env.EXP_NAME }}
+          if [ ! -f "$RESULT_FILENAME.json" ]; then
+            echo "Run failed: Benchmark result $RESULT_FILENAME.json not found." >&2
+            exit 1
+          fi
+
+  bmk-sweep-test-gptoss:
+    runs-on: ${{ inputs.runner }}
+
+    strategy:
+      fail-fast: false
+      matrix:
+        conc: [4, 8, 16, 32, 64]
+    name: 'gptoss ${{ inputs.runner }} (tp8 , conc${{ matrix.conc }})'
+
+    env:
+      EXP_NAME: 'gptoss_test'
+      IMAGE: ${{ inputs.image-gptoss }}
+      CONC: ${{ matrix.conc }}
+
+    steps:
+      - name: Resource cleanup
+        run: |
+          if command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; then
+            echo "Cleaning Docker resource ..."
+            docker ps -aq | xargs -r docker rm -f
+            docker network prune -f
+            while [ -n "$(docker ps -aq)" ]; do
+              sleep 5
+            done
+          fi
+          if command -v squeue >/dev/null 2>&1; then
+            echo "Cleaning Slurm resource ..."
+            scancel -u $USER
+            while [ -n "$(squeue -u $USER --noheader --format='%i')" ]; do
+              squeue -u $USER
+              sleep 5
+            done
+          fi
+
+      - uses: actions/checkout@v3
+        with:
+          token: ${{ secrets.REPO_PAT }}
+          fetch-depth: 0
+
+      - name: Set config variables
+        run: |
+          FRAMEWORK=$([[ ${{ inputs.runner }} == *trt ]] && printf "trt" || printf "")
+          echo "FRAMEWORK=${FRAMEWORK}" >> $GITHUB_ENV
+
+          RESULT_FILENAME=${{ env.EXP_NAME }}_tp${{ env.TP }}_conc${{ env.CONC }}_${{ runner.name }}
+          echo "RESULT_FILENAME=${RESULT_FILENAME}" >> $GITHUB_ENV
+
+          echo "MODEL=openai/gpt-oss-120b" >> $GITHUB_ENV
+
+      - name: Launch job script - gptoss
         run: |
           RUNNER_NAME=${{ runner.name }}
           bash ./runners/launch_${RUNNER_NAME%%_*}*.sh ${{ env.EXP_NAME }}
