Added not result file failure mode.

diff --git a/.github/workflows/gpu-sweep-test.yml b/.github/workflows/gpu-sweep-test.yml
--- a/.github/workflows/gpu-sweep-test.yml
+++ b/.github/workflows/gpu-sweep-test.yml
@@ -107,6 +107,10 @@ jobs:
         run: |
           RUNNER_NAME=${{ runner.name }}
           bash ./runners/launch_${RUNNER_NAME%%_*}*.sh ${{ env.EXP_NAME }}
+          if [ ! -f "$RESULT_FILENAME.json" ]; then
+            echo "Run failed: Benchmark result $RESULT_FILENAME.json not found." >&2
+            exit 1
+          fi
 
   bmk-sweep-test-dsr1:
     runs-on: ${{ inputs.runner }}
@@ -161,3 +165,7 @@ jobs:
         run: |
           RUNNER_NAME=${{ runner.name }}
           bash ./runners/launch_${RUNNER_NAME%%_*}*.sh ${{ env.EXP_NAME }}
+          if [ ! -f "$RESULT_FILENAME.json" ]; then
+            echo "Run failed: Benchmark result $RESULT_FILENAME.json not found." >&2
+            exit 1
+          fi
diff --git a/.github/workflows/runner-smoke-test.yml b/.github/workflows/runner-smoke-test.yml
--- a/.github/workflows/runner-smoke-test.yml
+++ b/.github/workflows/runner-smoke-test.yml
@@ -81,3 +81,7 @@ jobs:
           RUNNER_NAME=${{ inputs.runner }}
           MODEL_HANDLE=$([[ ${{ env.MODEL }} == *70B* ]] && printf '70b' || printf 'dsr1')
           bash ./runners/launch_${RUNNER_NAME%%_*}*.sh $MODEL_HANDLE
+          if [ ! -f "$RESULT_FILENAME.json" ]; then
+            echo "Run failed: Benchmark result $RESULT_FILENAME.json not found." >&2
+            exit 1
+          fi
