Added all gpus.

diff --git a/.github/workflows/model-sweep-test.yml b/.github/workflows/model-sweep-test.yml
--- a/.github/workflows/model-sweep-test.yml
+++ b/.github/workflows/model-sweep-test.yml
@@ -52,30 +52,6 @@ env:
   TP: 8
   CONC: 4
 
-x-common-steps:
-  - &resource-cleanup:
-    name: Resource cleanup
-    if: ${{ matrix.config.mname == github.event.inputs.model }}
-    run: |
-      if command -v docker >/dev/null 2>&1; then
-        echo "[Docker] Cleaning up resources ..."
-        docker ps -aq | xargs -r docker rm -f
-        docker network prune -f
-        while [ -n "$(docker ps -aq)" ]; do
-          docker ps -a
-          sleep 5
-        done
-      fi
-      if command -v squeue >/dev/null 2>&1; then
-        echo "[Slurm] Cleaning up resources ..."
-        scancel -u $USER
-        while [ -n "$(squeue -u $USER --noheader --format='%i')" ]; do
-          squeue -u $USER
-          sleep 5
-        done
-      fi
-
-
 jobs:
   bmk_h100:
     if: ${{ github.event.inputs.run_h100 }}
@@ -83,8 +59,8 @@ jobs:
       fail-fast: false
       matrix:
         runner:
-          - 'h100-cr_0'
-          - 'h100-cr_1'
+          # - 'h100-cr_0'
+          # - 'h100-cr_1'
           - 'h100-cw_0'
           - 'h100-cw_1'
         config:
@@ -109,7 +85,412 @@ jobs:
           echo "github.event.inputs.model = ${{ github.event.inputs.model }}"
           echo "matrix.config.mname = ${{ matrix.config.mname }}"
 
-      - *resource-cleanup
+      - name: Resource cleanup
+        if: ${{ matrix.config.mname == github.event.inputs.model }}
+        run: |
+          if command -v docker >/dev/null 2>&1; then
+            echo "[Docker] Cleaning up resources ..."
+            docker ps -aq | xargs -r docker rm -f
+            docker network prune -f
+            while [ -n "$(docker ps -aq)" ]; do
+              docker ps -a
+              sleep 5
+            done
+          fi
+          if command -v squeue >/dev/null 2>&1; then
+            echo "[Slurm] Cleaning up resources ..."
+            scancel -u $USER
+            while [ -n "$(squeue -u $USER --noheader --format='%i')" ]; do
+              squeue -u $USER
+              sleep 5
+            done
+          fi
+
+      - uses: actions/checkout@v3
+        if: ${{ matrix.config.mname == github.event.inputs.model }}
+        with:
+          token: ${{ secrets.REPO_PAT }}
+          fetch-depth: 0
+
+      - name: Run benchmark script
+        if: ${{ matrix.config.mname == github.event.inputs.model }}
+        run: |
+          echo "RESULT_FILENAME=${EXP_NAME}_tp${TP}_conc${CONC}_${RUNNER_NAME}" >> $GITHUB_ENV
+          bash ./runners/launch_${RUNNER_NAME%%_*}*.sh $EXP_NAME
+          if [ ! -f "$RESULT_FILENAME.json" ]; then
+            echo "Run failed: Benchmark result $RESULT_FILENAME.json not found." >&2
+            exit 1
+          fi
+
+  bmk_h200:
+    if: ${{ github.event.inputs.run_h200 }}
+    strategy:
+      fail-fast: false
+      matrix:
+        runner:
+          - 'h200-cw_0'
+          - 'h200-cw_1'
+          - 'h200-nb_0'
+          - 'h200-nb_1'
+          - 'h200-nb_2'
+          - 'h200-nb_3'
+          - 'h200-nv_0'
+          - 'h200-nv_1'
+          - 'h200-nv_2'
+          - 'h200-nv_3'
+        config:
+          - { 'exp-name': '70b_test', 'image': 'kedarpotdar147/vllm0.1:latest', 'model': 'nvidia/Llama-3.3-70B-Instruct-FP8' , 'mname': 'LLaMA 70B' }
+          - { 'exp-name': 'dsr1_test', 'image': 'lmsysorg/sglang:v0.4.9.post1-cu126', 'model': 'deepseek-ai/DeepSeek-R1-0528' , 'mname': 'DeepSeek R1' }
+          - { 'exp-name': 'gptoss_test', 'image': 'kedarpotdar147/vllm0.1:latest', 'model': 'openai/gpt-oss-120B', 'mname': 'gpt-oss 120B' }
+
+    runs-on: ${{ matrix.runner }}
+    name: '${{ matrix.config.mname }} - ${{ matrix.runner }}'
+
+    env:
+      RUNNER_NAME: ${{ matrix.runner }}
+      EXP_NAME: ${{ matrix.config.exp-name }}
+      IMAGE: ${{ matrix.config.image }}
+      MODEL: ${{ matrix.config.model }}
+
+    steps:
+      - name: Debug step
+        run: |
+          echo "RUNNER_NAME=$RUNNER_NAME"
+          echo "RESULT_FILENAME=${EXP_NAME}_tp${TP}_conc${CONC}_${RUNNER_NAME}"
+          echo "Script filepath: /runners/launch_${RUNNER_NAME%%_*}*.sh"
+          echo "github.event.inputs.model = ${{ github.event.inputs.model }}"
+          echo "matrix.config.mname = ${{ matrix.config.mname }}"
+
+      - name: Resource cleanup
+        if: ${{ matrix.config.mname == github.event.inputs.model }}
+        run: |
+          if command -v docker >/dev/null 2>&1; then
+            echo "[Docker] Cleaning up resources ..."
+            docker ps -aq | xargs -r docker rm -f
+            docker network prune -f
+            while [ -n "$(docker ps -aq)" ]; do
+              docker ps -a
+              sleep 5
+            done
+          fi
+          if command -v squeue >/dev/null 2>&1; then
+            echo "[Slurm] Cleaning up resources ..."
+            scancel -u $USER
+            while [ -n "$(squeue -u $USER --noheader --format='%i')" ]; do
+              squeue -u $USER
+              sleep 5
+            done
+          fi
+
+      - uses: actions/checkout@v3
+        if: ${{ matrix.config.mname == github.event.inputs.model }}
+        with:
+          token: ${{ secrets.REPO_PAT }}
+          fetch-depth: 0
+
+      - name: Run benchmark script
+        if: ${{ matrix.config.mname == github.event.inputs.model }}
+        run: |
+          echo "RESULT_FILENAME=${EXP_NAME}_tp${TP}_conc${CONC}_${RUNNER_NAME}" >> $GITHUB_ENV
+          bash ./runners/launch_${RUNNER_NAME%%_*}*.sh $EXP_NAME
+          if [ ! -f "$RESULT_FILENAME.json" ]; then
+            echo "Run failed: Benchmark result $RESULT_FILENAME.json not found." >&2
+            exit 1
+          fi
+
+  bmk_b200:
+    if: ${{ github.event.inputs.run_b200 }}
+    strategy:
+      fail-fast: false
+      matrix:
+        runner:
+          - 'b200-nv_0'
+          - 'b200-nv_1'
+          - 'b200-tg_0'
+        config:
+          - { 'exp-name': '70b_test', 'image': 'kedarpotdar147/vllm:05', 'model': 'nvidia/Llama-3.3-70B-Instruct-FP8' , 'mname': 'LLaMA 70B' }
+          - { 'exp-name': 'dsr1_test', 'image': 'lmsysorg/sglang:v0.5.0rc1-cu128-b200', 'model': 'deepseek-ai/DeepSeek-R1-0528' , 'mname': 'DeepSeek R1' }
+          - { 'exp-name': 'gptoss_test', 'image': 'kedarpotdar147/vllm:05', 'model': 'openai/gpt-oss-120B', 'mname': 'gpt-oss 120B' }
+
+    runs-on: ${{ matrix.runner }}
+    name: '${{ matrix.config.mname }} - ${{ matrix.runner }}'
+
+    env:
+      RUNNER_NAME: ${{ matrix.runner }}
+      EXP_NAME: ${{ matrix.config.exp-name }}
+      IMAGE: ${{ matrix.config.image }}
+      MODEL: ${{ matrix.config.model }}
+
+    steps:
+      - name: Debug step
+        run: |
+          echo "RUNNER_NAME=$RUNNER_NAME"
+          echo "RESULT_FILENAME=${EXP_NAME}_tp${TP}_conc${CONC}_${RUNNER_NAME}"
+          echo "Script filepath: /runners/launch_${RUNNER_NAME%%_*}*.sh"
+          echo "github.event.inputs.model = ${{ github.event.inputs.model }}"
+          echo "matrix.config.mname = ${{ matrix.config.mname }}"
+
+      - name: Resource cleanup
+        if: ${{ matrix.config.mname == github.event.inputs.model }}
+        run: |
+          if command -v docker >/dev/null 2>&1; then
+            echo "[Docker] Cleaning up resources ..."
+            docker ps -aq | xargs -r docker rm -f
+            docker network prune -f
+            while [ -n "$(docker ps -aq)" ]; do
+              docker ps -a
+              sleep 5
+            done
+          fi
+          if command -v squeue >/dev/null 2>&1; then
+            echo "[Slurm] Cleaning up resources ..."
+            scancel -u $USER
+            while [ -n "$(squeue -u $USER --noheader --format='%i')" ]; do
+              squeue -u $USER
+              sleep 5
+            done
+          fi
+
+      - uses: actions/checkout@v3
+        if: ${{ matrix.config.mname == github.event.inputs.model }}
+        with:
+          token: ${{ secrets.REPO_PAT }}
+          fetch-depth: 0
+
+      - name: Run benchmark script
+        if: ${{ matrix.config.mname == github.event.inputs.model }}
+        run: |
+          echo "RESULT_FILENAME=${EXP_NAME}_tp${TP}_conc${CONC}_${RUNNER_NAME}" >> $GITHUB_ENV
+          bash ./runners/launch_${RUNNER_NAME%%_*}*.sh $EXP_NAME
+          if [ ! -f "$RESULT_FILENAME.json" ]; then
+            echo "Run failed: Benchmark result $RESULT_FILENAME.json not found." >&2
+            exit 1
+          fi
+
+  bmk_mi300x:
+    if: ${{ github.event.inputs.run_mi300x }}
+    strategy:
+      fail-fast: false
+      matrix:
+        runner:
+          - 'mi300x-amd_0'
+          - 'mi300x-amd_1'
+          - 'mi300x-amd_2'
+          - 'mi300x-amd_3'
+          - 'mi300x-amd_4'
+          - 'mi300x-cr_0'
+        config:
+          - { 'exp-name': '70b_test', 'image': 'rocm/7.0-preview:rocm7.0_preview_ubuntu_22.04_vllm_0.10.1_instinct_rc1', 'model': 'nvidia/Llama-3.3-70B-Instruct-FP8' , 'mname': 'LLaMA 70B' }
+          - { 'exp-name': 'dsr1_test', 'image': 'rocm/7.0-preview:rocm7.0_preview_ubuntu_22.04_sgl-dev-v0.5.2rc2-mi30x_rc1', 'model': 'deepseek-ai/DeepSeek-R1-0528' , 'mname': 'DeepSeek R1' }
+          - { 'exp-name': 'gptoss_test', 'image': 'rocm/vllm-dev:open-mi300-08052025', 'model': 'openai/gpt-oss-120B', 'mname': 'gpt-oss 120B' }
+
+    runs-on: ${{ matrix.runner }}
+    name: '${{ matrix.config.mname }} - ${{ matrix.runner }}'
+
+    env:
+      RUNNER_NAME: ${{ matrix.runner }}
+      EXP_NAME: ${{ matrix.config.exp-name }}
+      IMAGE: ${{ matrix.config.image }}
+      MODEL: ${{ matrix.config.model }}
+
+    steps:
+      - name: Debug step
+        run: |
+          echo "RUNNER_NAME=$RUNNER_NAME"
+          echo "RESULT_FILENAME=${EXP_NAME}_tp${TP}_conc${CONC}_${RUNNER_NAME}"
+          echo "Script filepath: /runners/launch_${RUNNER_NAME%%_*}*.sh"
+          echo "github.event.inputs.model = ${{ github.event.inputs.model }}"
+          echo "matrix.config.mname = ${{ matrix.config.mname }}"
+
+      - name: Resource cleanup
+        if: ${{ matrix.config.mname == github.event.inputs.model }}
+        run: |
+          if command -v docker >/dev/null 2>&1; then
+            echo "[Docker] Cleaning up resources ..."
+            docker ps -aq | xargs -r docker rm -f
+            docker network prune -f
+            while [ -n "$(docker ps -aq)" ]; do
+              docker ps -a
+              sleep 5
+            done
+          fi
+          if command -v squeue >/dev/null 2>&1; then
+            echo "[Slurm] Cleaning up resources ..."
+            scancel -u $USER
+            while [ -n "$(squeue -u $USER --noheader --format='%i')" ]; do
+              squeue -u $USER
+              sleep 5
+            done
+          fi
+
+      - uses: actions/checkout@v3
+        if: ${{ matrix.config.mname == github.event.inputs.model }}
+        with:
+          token: ${{ secrets.REPO_PAT }}
+          fetch-depth: 0
+
+      - name: Run benchmark script
+        if: ${{ matrix.config.mname == github.event.inputs.model }}
+        run: |
+          echo "RESULT_FILENAME=${EXP_NAME}_tp${TP}_conc${CONC}_${RUNNER_NAME}" >> $GITHUB_ENV
+          bash ./runners/launch_${RUNNER_NAME%%_*}*.sh $EXP_NAME
+          if [ ! -f "$RESULT_FILENAME.json" ]; then
+            echo "Run failed: Benchmark result $RESULT_FILENAME.json not found." >&2
+            exit 1
+          fi
+
+  bmk_mi325x:
+    if: ${{ github.event.inputs.run_mi325x }}
+    strategy:
+      fail-fast: false
+      matrix:
+        runner:
+          - 'mi325x-amd_0'
+          - 'mi325x-tw_0'
+          - 'mi325x-tw_1'
+          - 'mi325x-tw_2'
+          - 'mi325x-tw_3'
+        config:
+          - {
+            'exp-name': '70b_test',
+            'image': 'rocm/7.0-preview:rocm7.0_preview_ubuntu_22.04_vllm_0.10.1_instinct_rc1',
+            'model': 'nvidia/Llama-3.3-70B-Instruct-FP8',
+            'mname': 'LLaMA 70B'
+          }
+          - {
+            'exp-name': 'dsr1_test',
+            'image': 'rocm/7.0-preview:rocm7.0_preview_ubuntu_22.04_sgl-dev-v0.5.2rc2-mi30x_rc1',
+            'model': 'deepseek-ai/DeepSeek-R1-0528',
+            'mname': 'DeepSeek R1'
+          }
+          - {
+            'exp-name': 'gptoss_test',
+            'image': 'rocm/vllm-dev:open-mi300-08052025',
+            'model': 'openai/gpt-oss-120B',
+            'mname': 'gpt-oss 120B'
+          }
+
+    runs-on: ${{ matrix.runner }}
+    name: '${{ matrix.config.mname }} - ${{ matrix.runner }}'
+
+    env:
+      RUNNER_NAME: ${{ matrix.runner }}
+      EXP_NAME: ${{ matrix.config.exp-name }}
+      IMAGE: ${{ matrix.config.image }}
+      MODEL: ${{ matrix.config.model }}
+
+    steps:
+      - name: Debug step
+        run: |
+          echo "RUNNER_NAME=$RUNNER_NAME"
+          echo "RESULT_FILENAME=${EXP_NAME}_tp${TP}_conc${CONC}_${RUNNER_NAME}"
+          echo "Script filepath: /runners/launch_${RUNNER_NAME%%_*}*.sh"
+          echo "github.event.inputs.model = ${{ github.event.inputs.model }}"
+          echo "matrix.config.mname = ${{ matrix.config.mname }}"
+
+      - name: Resource cleanup
+        if: ${{ matrix.config.mname == github.event.inputs.model }}
+        run: |
+          if command -v docker >/dev/null 2>&1; then
+            echo "[Docker] Cleaning up resources ..."
+            docker ps -aq | xargs -r docker rm -f
+            docker network prune -f
+            while [ -n "$(docker ps -aq)" ]; do
+              docker ps -a
+              sleep 5
+            done
+          fi
+          if command -v squeue >/dev/null 2>&1; then
+            echo "[Slurm] Cleaning up resources ..."
+            scancel -u $USER
+            while [ -n "$(squeue -u $USER --noheader --format='%i')" ]; do
+              squeue -u $USER
+              sleep 5
+            done
+          fi
+
+      - uses: actions/checkout@v3
+        if: ${{ matrix.config.mname == github.event.inputs.model }}
+        with:
+          token: ${{ secrets.REPO_PAT }}
+          fetch-depth: 0
+
+      - name: Run benchmark script
+        if: ${{ matrix.config.mname == github.event.inputs.model }}
+        run: |
+          echo "RESULT_FILENAME=${EXP_NAME}_tp${TP}_conc${CONC}_${RUNNER_NAME}" >> $GITHUB_ENV
+          bash ./runners/launch_${RUNNER_NAME%%_*}*.sh $EXP_NAME
+          if [ ! -f "$RESULT_FILENAME.json" ]; then
+            echo "Run failed: Benchmark result $RESULT_FILENAME.json not found." >&2
+            exit 1
+          fi
+
+  bmk_mi355x:
+    if: ${{ github.event.inputs.run_mi355x }}
+    strategy:
+      fail-fast: false
+      matrix:
+        runner:
+          - 'mi355x-amd_0'
+          - 'mi355x-amd_1'
+        config:
+          - {
+            'exp-name': '70b_test',
+            'image': 'rocm/7.0-preview:rocm7.0_preview_ubuntu_22.04_vllm_0.10.1_instinct_rc1',
+            'model': 'nvidia/Llama-3.3-70B-Instruct-FP8',
+            'mname': 'LLaMA 70B'
+          }
+          - {
+            'exp-name': 'dsr1_test',
+            'image': 'lmsysorg/sglang:v0.5.1.post2-rocm700-mi35x',
+            'model': 'deepseek-ai/DeepSeek-R1-0528',
+            'mname': 'DeepSeek R1'
+          }
+          - {
+            'exp-name': 'gptoss_test',
+            'image': 'rocm/vllm-dev:open-mi355-08052025',
+            'model': 'openai/gpt-oss-120B',
+            'mname': 'gpt-oss 120B'
+          }
+
+    runs-on: ${{ matrix.runner }}
+    name: '${{ matrix.config.mname }} - ${{ matrix.runner }}'
+
+    env:
+      RUNNER_NAME: ${{ matrix.runner }}
+      EXP_NAME: ${{ matrix.config.exp-name }}
+      IMAGE: ${{ matrix.config.image }}
+      MODEL: ${{ matrix.config.model }}
+
+    steps:
+      - name: Debug step
+        run: |
+          echo "RUNNER_NAME=$RUNNER_NAME"
+          echo "RESULT_FILENAME=${EXP_NAME}_tp${TP}_conc${CONC}_${RUNNER_NAME}"
+          echo "Script filepath: /runners/launch_${RUNNER_NAME%%_*}*.sh"
+          echo "github.event.inputs.model = ${{ github.event.inputs.model }}"
+          echo "matrix.config.mname = ${{ matrix.config.mname }}"
+
+      - name: Resource cleanup
+        if: ${{ matrix.config.mname == github.event.inputs.model }}
+        run: |
+          if command -v docker >/dev/null 2>&1; then
+            echo "[Docker] Cleaning up resources ..."
+            docker ps -aq | xargs -r docker rm -f
+            docker network prune -f
+            while [ -n "$(docker ps -aq)" ]; do
+              docker ps -a
+              sleep 5
+            done
+          fi
+          if command -v squeue >/dev/null 2>&1; then
+            echo "[Slurm] Cleaning up resources ..."
+            scancel -u $USER
+            while [ -n "$(squeue -u $USER --noheader --format='%i')" ]; do
+              squeue -u $USER
+              sleep 5
+            done
+          fi
 
       - uses: actions/checkout@v3
         if: ${{ matrix.config.mname == github.event.inputs.model }}
